# Generated by Django 4.1.1 on 2022-11-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_snippet_code_alter_snippet_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Публичный'),
        ),
    ]
